### ISSUE TITLE
Refamiliarization with codebase

### ISSUE THREAD

**Issue by Zenny00** [Salisbury-University/textual#19]
Picking up where we left off last semester will take some work. Time needs to be spent reviewing our previous work and becoming reacquainted with the code written during the previous sprints. Doing this will allow us to make better choices about the remaining tasks we need to complete for the project.

**Comment by cksmith21** [comment]
<img width="475" alt="Screenshot 2023-02-01 at 10 08 58" src="https://user-images.githubusercontent.com/43646917/216081021-64632e22-1577-4374-ac00-9d01af3bc656.png">

**Comment by Zenny00** [comment]
![image](https://user-images.githubusercontent.com/99524099/216185563-f6de0d2c-33d9-4433-9ccf-fc096348bd35.png)
